TEST: check compatibility of new cli behavior with productization
redhat-developer/rhdh pull request #1799
Opened 2024-10-21 17:25 UTC by davidfestal

## Description

This pull request is to test weather the proctization build pipeline supports the new default behavior of the export dynamic comment (without the --no-embed-as-dependencies flag).

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-10-21 20:16 UTC, nickboldt commented
for which JIRA is this?

2024-10-23 12:59 UTC, nickboldt requested changes
1. please link to a JIRA
2. this won't demonstate if cachi2 works with the changes because we can't enable cachi2 until we move to Yarn 3 in main - see https://github.com/janus-idp/backstage-showcase/pull/1810
3. once that's merged and working, THEN we can turn on hermetic builds and see what breaks downstream, get it working with the current setup migrated from cachito to cachi2, and...
4. THEN we can merge this and see what happens downstream

2025-01-21 21:32 UTC, nickboldt commented
Since we've long since moved to Yarn 3, my previous objections no longer apply

> 3\. turn on hermetic builds and see what breaks downstream, get it working with the current setup migrated from cachito to cachi2, and...

This is still not yet working due to node-gyp and playwright. See latest in https://issues.redhat.com/browse/RHIDP-4014

But if you still need this, and can rebase it to fix conflicts, we can merge it.

2025-01-22 01:28 UTC, coreydaley commented
Closed per conversation with @davidfestal

2025-01-22 01:28 UTC, closed without merging